### ISSUE TITLE
Tkinter not found when running lnp

### ISSUE THREAD

**Issue by ScreamingHawk** [McArcady/lnp-forge#19]
Following the build instructions and leaving all the configuration the same gets me to this error when running `./startlnp.sh`

```
['Traceback (most recent call last):\n', '  File "./launch.py", line 12, in <module>\n    lnp.PyLNP()\n', '  File ".build/src/lnp-0.14a/core/lnp.py", line 119, in __init__\n
   self.initialize_ui()\n', '  File ".build/src/lnp-0.14a/core/lnp.py", line 211, in initialize_ui\n    from tkgui.tkgui import TkGui\n', '  File "./tkgui/tkgui.py", line 16, in <module>\n    from . import controls, binding\n', '  File "./tkgui/controls.py", line 11, in <module>\n    from . import binding\n', '  File "./tkgui/binding.py", line 18, in <module>\n
  from Tkinter import END\n', '  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>\n    raise ImportError, str(msg) + \', please install the python-tk package\'\n', 'ImportError: No module named _tkinter, please install the python-tk package\n']
```

I noticed Tkinter was found during the installation process, not sure why this error is happening now. Perhaps the initial check looked at Python3 modules? There's something to fix here either way. 

I installed Tkinter and it is running fine now.

**Comment by McArcady** [comment]
Thanks for the feedback.
The python2 dependencies were removed since the LNP should soon drop support for it.
It will be added in the wiki.
