### ISSUE TITLE
Does not find dwarf fortress

### ISSUE THREAD

**Issue by Enerccio** [McArcady/lnp-forge#25]
The created lnp does not launch because it can't find dwarf fortress:

    ERROR: Could not find any Dwarf Fortress installations.
    ['Traceback (most recent call last):\n', '  File "./launch.py", line 12, in <module>\n    lnp.PyLNP()\n', '  File "/opt/lnp/core/lnp.py", line 113, in __init__\n    self.initialize_program()\n', '  File "/opt/lnp/core/lnp.py", line 132, in initialize_program\n    self.detect_basedir()\n', '  File "/opt/lnp/core/lnp.py", line 309, in detect_basedir\n    sys.exit(2)\n', 'SystemExit: 2\n']

**Comment by Enerccio** [comment]
Nevermind, it was permissions issue
