### ISSUE TITLE
It won't configure terminal

### ISSUE THREAD

**Issue by Erwbrad** [McArcady/lnp-forge#64]
```
Running PyLNP 0.14a (OS: linux, Compiled: False)
WARNING: JSONConfiguration: File PyLNP.user does not exist
INFO: Installing extras content for first time
WARNING: Could not determine installed graphics, tileset is curses_640x300.png/curses_square_16x16.png
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/tmp/lnp-2u08lE/core/launcher.py", line 52, in run_df
    result = run_program(executable, force, True, spawn_terminal)
  File "/tmp/lnp-2u08lE/core/launcher.py", line 91, in run_program
    run_args = terminal.get_terminal_command([path,])
  File "/tmp/lnp-2u08lE/core/terminal.py", line 30, in get_terminal_command
    raise Exception(
Exception: No terminal configured! Use File > Configure Terminal.
```

this is what my stderr.txt says

**Comment by McArcady** [comment]
Configure a terminal in the 'Terminal' menu.
You may choose 'custom command' with this:
`xterm -e $`
